[build]
  # 建置命令
  command = "npm run build"
  
  # 發布目錄
  publish = ".next"

[build.environment]
  # 環境變數
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# 重定向規則
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# 處理 Next.js 路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 環境變數（需要設置 QuestPDF API URL）
[context.production.environment]
  NEXT_PUBLIC_QUESTPDF_API_URL = "https://your-railway-app.railway.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_QUESTPDF_API_URL = "https://your-railway-app.railway.app" 