[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.install]
cmds = [
  "dotnet restore",
  "dotnet build -c Release",
  "dotnet publish -c Release -o ./publish"
]

[start]
cmd = "dotnet QuestPdfApi.dll --urls http://0.0.0.0:$PORT"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT" 